FROM ubuntu:16.04
MAINTAINER wdg369@gmail.com

RUN apt-get update -y
RUN apt-get install -y language-pack-ko
RUN pip install --upgrade pip
RUN apt install python3.7

python
RUN pip install konlpy
RUN pip install emoji

WORKDIR /tc_tagger

RUN git clone https://github.com/kyle-bong/tc_tagger


RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8