FROM ubuntu:16.04
MAINTAINER wdg369@gmail.com

sudo apt-get install git
RUN git clone https://github.com/kyle-bong/tc_tagger
WORKDIR /tc_tagger

RUN pip install --upgrade pip
RUN apt install python3.7

RUN apt-get update -y
RUN apt-get install -y language-pack-ko

RUN pip install konlpy
RUN pip install emoji

RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8